[project]
name = "vick"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ben Evans", email = "ben@bluechimp.io" }
]
requires-python = ">=3.10"
dependencies = [
    "victron-ble>=0.9.3",
    "click>=8.1",
    "tomli>=2.0; python_version < '3.11'",
    "influxdb-client>=1.45",
    "prometheus-client>=0.20",
    "paho-mqtt>=2.1",
]

[project.scripts]
vick = "vick:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
